// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdwnoogsubyawnruqbxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkd25vb2dzdWJ5YXducnVxYnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Njk0OTEsImV4cCI6MjA2NTQ0NTQ5MX0.3cJ8ZSp0PFO3JMOWsxa7x8_d5DMf72ZqIqYu6ubp73M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);